### ISSUE TITLE
Can not enter Sym (similar to oth2 option won't accept 5 digital input)

### ISSUE THREAD

**Issue by mm36** [mrexodia/akt#10]
The Sym key I got is DD9DB75E.  It has 8 digits, but the textbox of KeyGen can only accept 7 digits.
Any way to work around?

**Comment by mrexodia** [comment]
I just merged #8, just recompile and it should work.

**Comment by mm36** [comment]
Recompiled with visual studio community 2019.  The input problem is still the same.  Please fix it.

**Comment by mrexodia** [comment]
Nope. This tool does not come with support.
